{===============================================================================

  StdApp Components™

  Copyright © 2026-present tinyBigGAMES™ LLC
  All Rights Reserved.

  See LICENSE for license information

 -------------------------------------------------------------------------------

  UTest.VFS - VFS + Raylib demo

  Packs the bin\res directory into a VPK archive, loads an image
  texture and music stream from it, and displays them in a raylib
  window. Demonstrates VFS archive packing, memory-mapped file
  access, and raylib integration with VPK-backed assets.

  Dependencies: StdApp.TestDemo, StdApp.VFS, StdApp.VirtualMemory,
    StdApp.Utils, StdApp.Console, raylib_static
  Notes: Requires raylib_static.pas (generated by CImporter test)
    to be added to the project.
===============================================================================}

unit UTest.VFS;

{$I StdApp.Defines.inc}

interface

uses
  StdApp.TestDemo,
  StdApp.VFS,
  StdApp.VirtualMemory,
  raylib_static;

type

  { TTestVFS }
  TTestVFS = class(TTestDemo)
  private
    FVFS: TVFS;
    FImageView: TVirtualMemoryView<Byte>;
    FMusicView: TVirtualMemoryView<Byte>;
    FTexture: Texture2D;
    FMusic: Music;
    FReady: Boolean;
  public
    constructor Create(); override;
    procedure OnSetup(); override;
    procedure OnShutdown(); override;
    procedure OnUpdate(const ADeltaTime: Double); override;
    procedure OnRender(); override;
  end;

implementation

uses
  System.SysUtils,
  System.IOUtils,
  StdApp.Utils,
  StdApp.Console;

{ TTestVFS }

constructor TTestVFS.Create();
begin
  inherited;
  Title := 'VFS + Raylib';
  Looping := True;
  FReady := False;
  FVFS := nil;
  FImageView := nil;
  FMusicView := nil;
end;

procedure TTestVFS.OnSetup();
var
  LExeDir: string;
  LVpkPath: string;
  LSourceDir: string;
  LImage: Image;
begin
  FVFS := TVFS.Create();

  LExeDir := TPath.GetDirectoryName(ParamStr(0));
  LVpkPath := TPath.Combine(LExeDir, 'res.vpk');

  // Pack res directory into VPK if not already present
  if not TFile.Exists(LVpkPath) then
  begin
    LSourceDir := TPath.Combine(LExeDir, 'res');
    if not TDirectory.Exists(LSourceDir) then
    begin
      TConsole.PrintLn(COLOR_RED + 'Source directory not found: %s',
        [LSourceDir]);
      Terminate();
      Exit;
    end;

    TConsole.PrintLn('Packing %s...', [LSourceDir]);
    if not FVFS.PackDirectory(LSourceDir, LVpkPath,
      procedure(const AInfo: TVFSPackInfo;
        var ACancel: Boolean; const AUserData: Pointer)
      begin
        if AInfo.Status = cpsFileEnd then
          TConsole.PrintLn('  %s', [AInfo.EntryPath]);
      end)
    then
    begin
      TConsole.PrintLn(COLOR_RED + 'Pack failed!');
      FlushErrors(FVFS.GetErrors());
      Terminate();
      Exit;
    end;
    TConsole.PrintLn(COLOR_GREEN + 'Packed to: %s', [LVpkPath]);
  end
  else
    TConsole.PrintLn('Found: %s', [LVpkPath]);

  // Open VPK archive
  if not FVFS.Open(LVpkPath) then
  begin
    TConsole.PrintLn(COLOR_RED + 'Failed to open VPK!');
    FlushErrors(FVFS.GetErrors());
    Terminate();
    Exit;
  end;
  TConsole.PrintLn(COLOR_GREEN + 'VPK opened: %d entries',
    [FVFS.EntryCount()]);

  // Load image from VPK
  try
    FImageView := FVFS.OpenFile('image/stdapp.png');
  except
    on E: Exception do
    begin
      TConsole.PrintLn(COLOR_RED +
        'image/stdapp.png not found: %s', [E.Message]);
      Terminate();
      Exit;
    end;
  end;

  // Load music from VPK (VFS must stay open for streaming)
  try
    FMusicView := FVFS.OpenFile('music/music.ogg');
  except
    on E: Exception do
    begin
      TConsole.PrintLn(COLOR_RED +
        'music/music.ogg not found: %s', [E.Message]);
      Terminate();
      Exit;
    end;
  end;

  TConsole.PrintLn(COLOR_GREEN + 'Assets loaded from VPK');

  // Init raylib window and audio
  InitWindow(800, 450, 'StdApp - VFS + Raylib Test');
  SetTargetFPS(60);
  InitAudioDevice();

  // Load texture from memory
  LImage := LoadImageFromMemory('.png',
    FImageView.Memory, Integer(FImageView.Size));
  FTexture := LoadTextureFromImage(LImage);
  UnloadImage(LImage);

  // Load and play music from memory
  FMusic := LoadMusicStreamFromMemory('.ogg',
    FMusicView.Memory, Integer(FMusicView.Size));
  PlayMusicStream(FMusic);

  FReady := True;
end;

procedure TTestVFS.OnUpdate(const ADeltaTime: Double);
begin
  if not FReady then
    Exit;

  UpdateMusicStream(FMusic);

  if WindowShouldClose() then
    Terminate();
end;

procedure TTestVFS.OnRender();
var
  LSrc: Rectangle;
  LDst: Rectangle;
  LOrigin: Vector2;
begin
  if not FReady then
    Exit;

  LSrc.x := 0;
  LSrc.y := 0;
  LSrc.width := FTexture.width;
  LSrc.height := FTexture.height;

  LDst.x := 0;
  LDst.y := 0;
  LDst.width := 800;
  LDst.height := 450;

  LOrigin.x := 0;
  LOrigin.y := 0;

  BeginDrawing();
  ClearBackground(RAYWHITE);
  DrawTexturePro(FTexture, LSrc, LDst, LOrigin, 0, WHITE);
  DrawText('Hello from StdApp VFS!', 280, 24, 20, DARKGRAY);
  DrawText('Image + Music loaded from VPK archive',
    220, 48, 16, GRAY);
  EndDrawing();
end;

procedure TTestVFS.OnShutdown();
begin
  if FReady then
  begin
    UnloadMusicStream(FMusic);
    UnloadTexture(FTexture);
    CloseAudioDevice();
    CloseWindow();
  end;

  FMusicView.Free();
  FImageView.Free();
  FVFS.Free();
end;

end.
